"""
Base strategy class defining the interface for all trading strategies.

This module provides an abstract base class that all trading strategies
must inherit from, ensuring consistent interfaces for signal generation,
position management, and execution.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime, date
from enum import Enum
from loguru import logger


class SignalType(Enum):
    """Types of trading signals."""
    ENTRY = "ENTRY"           # Open new position
    EXIT = "EXIT"             # Close existing position
    ADJUST = "ADJUST"         # Adjust position (roll, add, reduce)
    HOLD = "HOLD"             # Do nothing


class SignalDirection(Enum):
    """Direction of the signal."""
    LONG = "LONG"             # Buy/long position
    SHORT = "SHORT"           # Sell/short position
    NEUTRAL = "NEUTRAL"       # No directional bias


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.

    A signal contains all information needed to execute a trade,
    including entry/exit criteria, position sizing, and risk parameters.
    """

    # Identity (required fields first)
    signal_id: str
    strategy_name: str
    signal_type: SignalType
    direction: SignalDirection
    symbol: str

    # Timestamp (optional with default)
    generated_at: datetime = field(default_factory=datetime.now)

    # Entry/exit details
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    # Position sizing
    quantity: Optional[int] = None
    position_size_pct: Optional[float] = None  # % of portfolio

    # Options-specific (for wheel strategy)
    option_type: Optional[str] = None  # 'CALL' or 'PUT'
    strike: Optional[float] = None
    expiration: Optional[date] = None
    delta: Optional[float] = None

    # Strategy context
    confidence: float = 0.0  # 0.0 to 1.0
    priority: int = 0  # Higher = more urgent
    notes: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Related position
    position_id: Optional[str] = None

    def __repr__(self) -> str:
        """String representation of signal."""
        return (
            f"Signal({self.signal_type.value}, {self.symbol}, "
            f"{self.direction.value}, conf={self.confidence:.2f})"
        )


@dataclass
class PositionState:
    """
    Current state of a position managed by a strategy.

    Tracks all relevant information about an open position
    including entry details, current status, and P&L.
    """

    # Identity
    position_id: str
    strategy_name: str
    symbol: str

    # Position details
    direction: SignalDirection
    quantity: int
    entry_price: float
    entry_date: datetime

    # Current status
    current_price: float
    current_value: float
    unrealized_pnl: float
    unrealized_pnl_pct: float

    # Risk parameters
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    # Options-specific
    option_type: Optional[str] = None
    strike: Optional[float] = None
    expiration: Optional[date] = None
    days_to_expiration: Optional[int] = None

    # Management
    last_adjustment: Optional[datetime] = None
    adjustment_count: int = 0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def days_held(self) -> int:
        """Number of days position has been held."""
        return (datetime.now() - self.entry_date).days

    @property
    def is_profitable(self) -> bool:
        """Check if position is currently profitable."""
        return self.unrealized_pnl > 0

    def __repr__(self) -> str:
        """String representation of position."""
        return (
            f"Position({self.symbol}, {self.quantity} @ ${self.entry_price:.2f}, "
            f"P&L: ${self.unrealized_pnl:.2f} [{self.unrealized_pnl_pct:+.1f}%])"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement:
    1. generate_signals() - Produce trading signals
    2. manage_position() - Handle position management
    3. should_exit() - Determine exit conditions

    Optional methods to override:
    - validate_signal() - Additional signal validation
    - calculate_position_size() - Custom position sizing
    - on_fill() - React to order fills
    - on_error() - Handle errors
    """

    def __init__(self, name: str, config: Optional[Dict[str, Any]] = None):
        """
        Initialize base strategy.

        Args:
            name: Strategy name
            config: Strategy-specific configuration
        """
        self.name = name
        self.config = config or {}
        self.active_positions: Dict[str, PositionState] = {}
        self.signal_history: List[Signal] = []

        logger.info(f"Strategy '{name}' initialized with config: {config}")

    @abstractmethod
    async def generate_signals(
        self,
        market_data: Dict[str, Any],
        positions: List[PositionState]
    ) -> List[Signal]:
        """
        Generate trading signals based on market data.

        This is the core signal generation logic that each strategy
        must implement.

        Args:
            market_data: Current market data (quotes, options, IV, etc.)
            positions: Current open positions

        Returns:
            List of signals to execute
        """
        pass

    @abstractmethod
    async def manage_position(
        self,
        position: PositionState,
        market_data: Dict[str, Any]
    ) -> Optional[Signal]:
        """
        Manage an existing position.

        Determines if position should be adjusted, closed, or held.

        Args:
            position: Position to manage
            market_data: Current market data

        Returns:
            Signal if action needed, None to hold
        """
        pass

    @abstractmethod
    def should_exit(
        self,
        position: PositionState,
        market_data: Dict[str, Any]
    ) -> tuple[bool, str]:
        """
        Determine if position should be exited.

        Args:
            position: Position to check
            market_data: Current market data

        Returns:
            Tuple of (should_exit, reason)
        """
        pass

    def validate_signal(self, signal: Signal) -> tuple[bool, str]:
        """
        Validate a signal before execution.

        Override this method to add strategy-specific validation.

        Args:
            signal: Signal to validate

        Returns:
            Tuple of (is_valid, message)
        """
        # Basic validation
        if not signal.symbol:
            return False, "Symbol is required"

        if signal.signal_type == SignalType.ENTRY:
            if signal.quantity is None and signal.position_size_pct is None:
                return False, "Position size not specified"

        return True, "Signal is valid"

    def calculate_position_size(
        self,
        signal: Signal,
        portfolio_value: float,
        available_capital: float
    ) -> int:
        """
        Calculate position size for a signal.

        Override this method for custom position sizing logic.

        Args:
            signal: Signal to size
            portfolio_value: Total portfolio value
            available_capital: Available cash

        Returns:
            Quantity to trade
        """
        # If quantity already specified, use it
        if signal.quantity is not None:
            return signal.quantity

        # Use position size percentage
        if signal.position_size_pct is not None:
            target_value = portfolio_value * signal.position_size_pct

            if signal.entry_price:
                quantity = int(target_value / signal.entry_price)
                return max(1, quantity)

        # Default: use 10% of portfolio
        default_size = portfolio_value * 0.10
        if signal.entry_price:
            return max(1, int(default_size / signal.entry_price))

        return 1

    def add_position(self, position: PositionState) -> None:
        """
        Add a position to active tracking.

        Args:
            position: Position to track
        """
        self.active_positions[position.position_id] = position
        logger.info(f"Added position to {self.name}: {position}")

    def remove_position(self, position_id: str) -> Optional[PositionState]:
        """
        Remove a position from active tracking.

        Args:
            position_id: Position ID to remove

        Returns:
            Removed position or None
        """
        position = self.active_positions.pop(position_id, None)
        if position:
            logger.info(f"Removed position from {self.name}: {position}")
        return position

    def get_position(self, position_id: str) -> Optional[PositionState]:
        """
        Get a position by ID.

        Args:
            position_id: Position ID

        Returns:
            Position or None
        """
        return self.active_positions.get(position_id)

    def get_positions_for_symbol(self, symbol: str) -> List[PositionState]:
        """
        Get all positions for a symbol.

        Args:
            symbol: Symbol to filter by

        Returns:
            List of positions
        """
        return [
            pos for pos in self.active_positions.values()
            if pos.symbol == symbol
        ]

    async def on_fill(
        self,
        signal: Signal,
        filled_quantity: int,
        filled_price: float
    ) -> None:
        """
        Called when a signal's order is filled.

        Override to implement custom logic on fills.

        Args:
            signal: Original signal
            filled_quantity: Quantity filled
            filled_price: Fill price
        """
        logger.info(
            f"{self.name} - Order filled: {signal.symbol} "
            f"{filled_quantity} @ ${filled_price:.2f}"
        )

    async def on_error(
        self,
        signal: Signal,
        error: Exception
    ) -> None:
        """
        Called when a signal execution fails.

        Override to implement custom error handling.

        Args:
            signal: Failed signal
            error: Error that occurred
        """
        logger.error(
            f"{self.name} - Signal execution failed: {signal.symbol} - {error}"
        )

    def get_statistics(self) -> Dict[str, Any]:
        """
        Get strategy performance statistics.

        Returns:
            Dictionary of statistics
        """
        positions = list(self.active_positions.values())

        if not positions:
            return {
                'name': self.name,
                'active_positions': 0,
                'total_pnl': 0.0,
                'avg_pnl_pct': 0.0
            }

        total_pnl = sum(p.unrealized_pnl for p in positions)
        avg_pnl_pct = sum(p.unrealized_pnl_pct for p in positions) / len(positions)
        winning_positions = sum(1 for p in positions if p.is_profitable)

        return {
            'name': self.name,
            'active_positions': len(positions),
            'winning_positions': winning_positions,
            'win_rate': winning_positions / len(positions) if positions else 0,
            'total_pnl': total_pnl,
            'avg_pnl_pct': avg_pnl_pct,
            'largest_position': max(positions, key=lambda p: abs(p.unrealized_pnl)),
            'oldest_position': min(positions, key=lambda p: p.entry_date)
        }

    def __repr__(self) -> str:
        """String representation of strategy."""
        return f"{self.__class__.__name__}('{self.name}', positions={len(self.active_positions)})"
